version: "3.8"

services:
  gucl_db:
    container_name: gucl_database
    image: postgres:15.5-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  gucl_site:
    container_name: gucl_web
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - .:/app
    links:
      - gucl_db
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL_DOCKER}
