version: '3.8'

services:
  gucl_db:
    container_name: gucl_database
    image: postgres:15.5-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  gucl_site:
    container_name: gucl_web
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
